package probe

var tempQueries = map[string][]string{
	"first_name": 		  {"DataValue", "MiscDataDynamic", "DataName", "PlayerFirstName"},
	"surname":    		  {"DataValue", "MiscDataDynamic", "DataName", "PlayerLastName"},
	"xp":         		  {"DataValue", "MiscDataDynamic", "DataName", "ExperiencePoints"},
	"house":      		  {"DataValue", "MiscDataDynamic", "DataName", "HouseID"},
	"galleons":   		  {"Count", "InventoryDynamic", "CharacterID", "Player0", "ItemID", "Knuts"},
	"inventory_size":     {"DataValue", "MiscDataDynamic", "DataName", "BaseInventoryCapacity"},
	"talent_points":      {"DataValue", "MiscDataDynamic", "DataOwner", "Player0", "DataName", "PerkPoints"},
}

var queries = map[string]string{
	"inventory": `SELECT "ItemID", "Count" FROM "InventoryDynamic" WHERE "CharacterID" = "Player0" AND "HolderID" = "ResourceInventory" AND "ItemID" IS NOT NULL`,
	"wand":      `SELECT "DataValue" FROM "MiscDataDynamic" WHERE "DataOwner" = "Player" AND "DataName" = "%s"`,
}

var fmtWandParts = map[string]map[string]string{
	"WandBase": map[string]string{
		"T000_M00": "Notched, warm brown",
		"T000_M01": "Notched, light brown",
		"T000_M02": "Notched, dusty pink",
		"T001_M00": "Classic, grey",
		"T001_M01": "Classic, black",
		"T001_M02": "Classic, grey-brown",
		"T002_M00": "Soft spiral, light brown",
		"T002_M01": "Soft spiral, warm brown",
		"T002_M02": "Soft spiral, black",
		"T003_M00": "Spiral, ash brown",
		"T003_M01": "Spiral, green-grey",
		"T003_M02": "Spiral, dark brown",
		"T004_M00": "Stalk, honey brown",
		"T004_M01": "Stalk, dark brown",
		"T004_M02": "Stalk, warm brown",
		"T005_M00": "Ringed, dark brown",
		"T005_M01": "Ringed, pale brown",
		"T005_M02": "Ringed, buff",
		"T006_M00": "Crooked spiral, dark grey",
		"T006_M01": "Crooked spiral, warm brown",
		"T006_M02": "Crooked spiral, pale brown",
		"T007_M00": "Natural, grey",
		"T007_M01": "Natural, honey brown",
		"T007_M02": "Natural, warm brown",
	},
	"WandWood": map[string]string{
		"Wood_Acacia": "Acacia",
		"Wood_Alder": "Alder",
		"Wood_Ash": "Ash",
		"Wood_Beech": "Beech",
		"Wood_Blackthorn": "Blackthorn",
		"Wood_BlackWalnut": "Black walnut",
		"Wood_Cedar": "Cedar",
		"Wood_Cherry": "Cherry",
		"Wood_Chestnut": "Chestnut",
		"Wood_Cypress": "Cypress",
		"Wood_Dogwood": "Dogwood",
		"Wood_Ebony": "Ebony",
		"Wood_Elder": "Elder",
		"Wood_Elm": "Elm",
		"Wood_EnglishOak": "English oak",
		"Wood_Fir": "Fir",
		"Wood_Hawthorn": "Hawthorn",
		"Wood_Holly": "Holly",
		"Wood_Hazel": "Hazel",
		"Wood_Hornbeam": "Hornbeam",
		"Wood_Larch": "Larch",
		"Wood_Laurel": "Laurel",
		"Wood_Maple": "Maple",				
		"Wood_Pear": "Pear",
		"Wood_Pine": "Pine",
		"Wood_Poplar": "Poplar",
		"Wood_RedOak": "Red oak",
		"Wood_Redwood": "Redwood",
		"Wood_Rowan": "Rowan",
		"Wood_SilverLime": "Silver lime",
		"Wood_Spruce": "Spruce",
		"Wood_Sycamore": "Sycamore",
		"Wood_Vine": "Vine",
		"Wood_Walnut": "Walnut",
		"Wood_Willow": "Willow",
		"Wood_Yew": "Yew",

	},
	"WandCore": map[string]string{
		"DragonHeartstringCore": "Dragon heartstring",
		"PhoenixFeatherCore": "Phoenix feather",
		"UnicornHairCore": "Unicorn hair",
	},
	"WandLength": map[string]string{
		"NineAndAHalf": "9 ½",
		"NineAndThreeQuarters": "9 ¾",
		"ten": "10",
		"TenAndAQuarter": "10 ¼",
		"TenAndAHalf": "10 ½",
		"TenAndThreeQuarters": "10 ¾",
		"eleven": "11",
		"ElevenAndAQuarter": "11 ¼",
		"ElevenAndAHalf": "11 ½",
		"ElevenAndThreeQuarters": "11 ¾",
		"twelve": "12",	
		"TwelveAndAQuarter": "12 ¼",
		"TwelveAndAHalf": "12 ½",
		"TwelveAndThreeQuarters": "12 ¾",
		"Thirteen": "13",	
		"ThirteenAndAQuarter": "13 ¼",
		"ThirteenAndAHalf": "13 ½",
		"ThirteenAndThreeQuarters": "13 ¾",
		"Fourteen": "14",	
		"FourteenAndAQuarter": "14 ¼",
		"FourteenAndAHalf": "14 ½",
	},
	"WandFlex" : map[string]string{
		"Flexibility_Brittle": "Brittle",
		"Flexibility_FairlyBendy": "Fairly bendy",
		"Flexibility_Hard": "Flexibility hard",
		"Flexibility_Pliant": "Flexibility pliant",
		"Flexibility_QuiteBendy": "Quite bendy",
		"Flexibility_QuiteFlexible": "Quite flexible",
		"Flexibility_ReasonablySupple": "Reasonably supple",
		"Flexibility_Rigid": "Flexibility_Rigid",
		"Flexibility_SlightlySpringy": "Slightly springy",
		"Flexibility_SlightlyYielding": "Slightly yielding",
		"Flexibility_Solid": "Solid",
		"Flexibility_Stiff": "Stiff",
		"Flexibility_Supple": "Supple",
		"Flexibility_SurprisinglySwishy": "Surprisingly swishy",
		"Flexibility_Swishy": "Swishy",
		"Flexibility_Unbending": "Unbending",
		"Flexibility_Unyielding": "Unyielding",
		"Flexibility_VeryFlexible": "Very flexible",
	},
}